# Generated by Django 6.0 on 2025-12-04 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatequeseInfantilModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('data_nascimento', models.DateField()),
                ('naturalidade', models.CharField(blank=True, max_length=100, null=True)),
                ('nome_pai', models.CharField(blank=True, max_length=150, null=True)),
                ('nome_mae', models.CharField(blank=True, max_length=150, null=True)),
                ('endereco', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2)),
                ('celular_pai', models.CharField(blank=True, max_length=20, null=True)),
                ('celular_mae', models.CharField(blank=True, max_length=20, null=True)),
                ('batizado', models.BooleanField(default=False)),
                ('batizado_data', models.DateField(blank=True, null=True)),
                ('batizado_diocese', models.CharField(blank=True, max_length=150, null=True)),
                ('batizado_paroquia', models.CharField(blank=True, max_length=150, null=True)),
                ('batizado_celebrante', models.CharField(blank=True, max_length=150, null=True)),
                ('horario', models.CharField(choices=[('1', 'Pré-Catequese - Segunda às 19:30h'), ('2', 'Pré-Catequese - Terça às 19:30h'), ('3', 'Pré-Catequese - Sábado às 09h'), ('4', 'Pré-Catequese - Sábado às 10:30h'), ('5', '1a Etapa - Segunda às 19:30h'), ('6', '1a Etapa - Terça às 19:30h'), ('7', '1a Etapa - Quarta às 19:30h'), ('8', '1a Etapa - Sábado às 09h'), ('9', '1a Etapa - Sábado às 10:30h'), ('10', '12+ - Terça às 19:30h'), ('11', '12+ - Quinta ás 19:30h')], max_length=2)),
                ('possui_deficiencia', models.BooleanField(default=False)),
                ('descricao_deficiencia', models.TextField(blank=True, null=True)),
                ('possui_transtorno', models.BooleanField(default=False)),
                ('descricao_transtorno', models.TextField(blank=True, null=True)),
                ('medicamento_uso_continuo', models.BooleanField(default=False)),
                ('descricao_medicamento', models.TextField(blank=True, null=True)),
                ('medicamento_horario', models.CharField(blank=True, max_length=100, null=True)),
                ('acompanhamento_psicologico', models.BooleanField(default=False)),
                ('descricao_acompanhamento', models.TextField(blank=True, null=True)),
                ('nome_responsavel', models.CharField(max_length=150)),
                ('cpf_responsavel', models.CharField(max_length=14)),
                ('endereco_responsavel', models.CharField(max_length=255)),
                ('ficha_impressa', models.BooleanField(default=False)),
            ],
        ),
    ]
