# Generated by Django 6.0 on 2025-12-04 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catequeseinfantilmodel',
            name='celular_mae',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='catequeseinfantilmodel',
            name='celular_pai',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
