# Generated by Django 6.0 on 2025-12-04 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_catequeseinfantilmodel_celular_mae_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catequeseinfantilmodel',
            name='nome_mae',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='catequeseinfantilmodel',
            name='nome_pai',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
    ]
