# Generated by Django 6.0 on 2025-12-05 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_catequeseinfantilmodel_nome_mae_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrismaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('data_nascimento', models.DateField()),
                ('naturalidade', models.CharField(blank=True, max_length=100, null=True)),
                ('nome_pai', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('nome_mae', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('endereco', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2)),
                ('celular_pai', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('celular_mae', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('batizado', models.BooleanField(default=False)),
                ('batizado_data', models.DateField(blank=True, null=True)),
                ('batizado_diocese', models.CharField(blank=True, max_length=150, null=True)),
                ('batizado_paroquia', models.CharField(blank=True, max_length=150, null=True)),
                ('batizado_celebrante', models.CharField(blank=True, max_length=150, null=True)),
                ('primeira_eucaristia', models.BooleanField(default=False)),
                ('primeira_eucaristia_data', models.DateField(blank=True, null=True)),
                ('primeira_eucaristia_diocese', models.CharField(blank=True, max_length=150, null=True)),
                ('primeira_eucaristia_paroquia', models.CharField(blank=True, max_length=150, null=True)),
                ('primeira_eucaristia_celebrante', models.CharField(blank=True, max_length=150, null=True)),
                ('horario', models.CharField(choices=[('1', 'Quinta às 19:30h'), ('2', 'Sábado às 09h'), ('3', 'Sábado às 10:30h')], max_length=2)),
                ('padrinho_nome', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('padrinho_celular', models.CharField(blank=True, default='', max_length=20, null=True)),
            ],
        ),
    ]
