# Generated by Django 6.0 on 2025-12-05 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_crismamodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='crismamodel',
            name='ficha_impressa',
            field=models.BooleanField(default=False),
        ),
    ]
