# Generated by Django 6.0 on 2025-12-05 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_crismamodel_ficha_impressa'),
    ]

    operations = [
        migrations.AddField(
            model_name='crismamodel',
            name='cpf_responsavel',
            field=models.CharField(default='', max_length=14),
        ),
        migrations.AddField(
            model_name='crismamodel',
            name='endereco_responsavel',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='crismamodel',
            name='nome_responsavel',
            field=models.CharField(default='', max_length=150),
        ),
    ]
