# Generated by Django 6.0 on 2025-12-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_crismamodel_cpf_responsavel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catequeseinfantilmodel',
            name='celular_mae',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='catequeseinfantilmodel',
            name='celular_pai',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='catequeseinfantilmodel',
            name='nome_mae',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='catequeseinfantilmodel',
            name='nome_pai',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='crismamodel',
            name='celular_mae',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='crismamodel',
            name='celular_pai',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='crismamodel',
            name='nome_mae',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='crismamodel',
            name='nome_pai',
            field=models.CharField(default='', max_length=150),
        ),
    ]
