# Generated by Django 6.0 on 2025-12-05 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_catequeseinfantilmodel_celular_mae_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perseveranca_MEJ_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('data_nascimento', models.DateField()),
                ('naturalidade', models.CharField(blank=True, max_length=100, null=True)),
                ('nome_pai', models.CharField(default='', max_length=150)),
                ('nome_mae', models.CharField(default='', max_length=150)),
                ('endereco', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2)),
                ('celular_pai', models.CharField(default='', max_length=20)),
                ('celular_mae', models.CharField(default='', max_length=20)),
                ('batizado', models.BooleanField(default=False)),
                ('batizado_data', models.DateField(blank=True, null=True)),
                ('batizado_diocese', models.CharField(blank=True, max_length=150, null=True)),
                ('batizado_paroquia', models.CharField(blank=True, max_length=150, null=True)),
                ('batizado_celebrante', models.CharField(blank=True, max_length=150, null=True)),
                ('primeira_eucaristia', models.BooleanField(default=False)),
                ('primeira_eucaristia_data', models.DateField(blank=True, null=True)),
                ('primeira_eucaristia_diocese', models.CharField(blank=True, max_length=150, null=True)),
                ('primeira_eucaristia_paroquia', models.CharField(blank=True, max_length=150, null=True)),
                ('primeira_eucaristia_celebrante', models.CharField(blank=True, max_length=150, null=True)),
                ('horario', models.CharField(choices=[('1', 'Perseverança - Quinta às 19:30h')], max_length=2)),
                ('possui_deficiencia', models.BooleanField(default=False)),
                ('descricao_deficiencia', models.TextField(blank=True, null=True)),
                ('possui_transtorno', models.BooleanField(default=False)),
                ('descricao_transtorno', models.TextField(blank=True, null=True)),
                ('medicamento_uso_continuo', models.BooleanField(default=False)),
                ('descricao_medicamento', models.TextField(blank=True, null=True)),
                ('medicamento_horario', models.CharField(blank=True, max_length=100, null=True)),
                ('acompanhamento_psicologico', models.BooleanField(default=False)),
                ('descricao_acompanhamento', models.TextField(blank=True, null=True)),
                ('nome_responsavel', models.CharField(max_length=150)),
                ('cpf_responsavel', models.CharField(max_length=14)),
                ('endereco_responsavel', models.CharField(max_length=255)),
                ('ficha_impressa', models.BooleanField(default=False)),
                ('ficha_assinada', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='catequeseinfantilmodel',
            name='ficha_assinada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crismamodel',
            name='ficha_assinada',
            field=models.BooleanField(default=False),
        ),
    ]
