# Generated by Django 6.0 on 2025-12-05 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_perseveranca_mej_model_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatequeseAdultoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('data_nascimento', models.DateField()),
                ('naturalidade', models.CharField(blank=True, max_length=100, null=True)),
                ('nome_pai', models.CharField(default='', max_length=150)),
                ('nome_mae', models.CharField(default='', max_length=150)),
                ('endereco', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2)),
                ('estado_civil', models.CharField(max_length=50)),
                ('celular_pai', models.CharField(default='', max_length=20)),
                ('celular_mae', models.CharField(default='', max_length=20)),
                ('batizado', models.BooleanField(default=False)),
                ('batizado_data', models.DateField(blank=True, null=True)),
                ('batizado_diocese', models.CharField(blank=True, max_length=150, null=True)),
                ('batizado_paroquia', models.CharField(blank=True, max_length=150, null=True)),
                ('batizado_celebrante', models.CharField(blank=True, max_length=150, null=True)),
                ('primeira_eucaristia', models.BooleanField(default=False)),
                ('primeira_eucaristia_data', models.DateField(blank=True, null=True)),
                ('primeira_eucaristia_diocese', models.CharField(blank=True, max_length=150, null=True)),
                ('primeira_eucaristia_paroquia', models.CharField(blank=True, max_length=150, null=True)),
                ('primeira_eucaristia_celebrante', models.CharField(blank=True, max_length=150, null=True)),
                ('casado_igreja', models.BooleanField(default=False)),
                ('casado_igreja_data', models.DateField(blank=True, null=True)),
                ('casado_igreja_diocese', models.CharField(blank=True, max_length=150, null=True)),
                ('casado_igreja_paroquia', models.CharField(blank=True, max_length=150, null=True)),
                ('casado_igreja_celebrante', models.CharField(blank=True, max_length=150, null=True)),
                ('horario', models.CharField(choices=[('1', 'Terça às 19:30h'), ('2', 'Sábado às 08h')], max_length=2)),
                ('padrinho_nome', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('padrinho_celular', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('nome_responsavel', models.CharField(default='', max_length=150)),
                ('cpf_responsavel', models.CharField(default='', max_length=14)),
                ('endereco_responsavel', models.CharField(default='', max_length=255)),
                ('ficha_impressa', models.BooleanField(default=False)),
                ('ficha_assinada', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='perseveranca_mej_model',
            name='horario',
            field=models.CharField(choices=[('1', 'Perseverança - 11 a 14 anos - Quinta às 19:30h'), ('2', 'MEJ - 15 a 25 anos - Quinta às 19:30h')], max_length=2),
        ),
    ]
