# Generated by Django 6.0 on 2025-12-05 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_catequeseadultomodel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catequeseadultomodel',
            old_name='cpf_responsavel',
            new_name='cpf',
        ),
        migrations.RemoveField(
            model_name='catequeseadultomodel',
            name='endereco_responsavel',
        ),
        migrations.RemoveField(
            model_name='catequeseadultomodel',
            name='nome_responsavel',
        ),
    ]
