# Generated by Django 6.0 on 2025-12-05 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_cpf_responsavel_catequeseadultomodel_cpf_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catequeseadultomodel',
            old_name='celular_mae',
            new_name='celular',
        ),
        migrations.RemoveField(
            model_name='catequeseadultomodel',
            name='celular_pai',
        ),
    ]
