# Generated by Django 6.0 on 2025-12-10 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_catequeseadultomodel_criado_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crismamodel',
            name='acompanhamento_psicologico',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crismamodel',
            name='descricao_acompanhamento',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crismamodel',
            name='descricao_deficiencia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crismamodel',
            name='descricao_medicamento',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crismamodel',
            name='descricao_transtorno',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crismamodel',
            name='medicamento_horario',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='crismamodel',
            name='medicamento_uso_continuo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crismamodel',
            name='possui_deficiencia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crismamodel',
            name='possui_transtorno',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='perseveranca_mej_model',
            name='horario',
            field=models.CharField(choices=[('1', 'Perseverança e MEJ - 11 a 14 anos - Quinta às 19:30h'), ('2', 'MEJ - 15 a 25 anos - Quinta às 19:30h')], max_length=2),
        ),
    ]
