# Generated by Django 6.0 on 2026-01-12 01:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_crismamodel_acompanhamento_psicologico_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoivoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_noivo', models.CharField(max_length=150)),
                ('endereco_noivo', models.CharField(max_length=255)),
                ('celular_noivo', models.CharField(default='', max_length=20)),
                ('data_nascimento_noivo', models.DateField()),
                ('profissao_noivo', models.CharField(max_length=100)),
                ('local_trabalho_noivo', models.CharField(max_length=100)),
                ('religiao_noivo', models.CharField(max_length=100)),
                ('restricao_alimentar_noivo', models.CharField(max_length=100)),
                ('nome_pai_noivo', models.CharField(default='', max_length=150)),
                ('nome_mae_noivo', models.CharField(default='', max_length=150)),
                ('endereco_pais_noivo', models.CharField(max_length=255)),
                ('celular_pais_noivo', models.CharField(default='', max_length=20)),
                ('religiao_pais_noivo', models.CharField(max_length=100)),
                ('nome_noiva', models.CharField(max_length=150)),
                ('endereco_noiva', models.CharField(max_length=255)),
                ('celular_noiva', models.CharField(default='', max_length=20)),
                ('data_nascimento_noiva', models.DateField()),
                ('profissao_noiva', models.CharField(max_length=100)),
                ('local_trabalho_noiva', models.CharField(max_length=100)),
                ('religiao_noiva', models.CharField(max_length=100)),
                ('restricao_alimentar_noiva', models.CharField(max_length=100)),
                ('nome_pai_noiva', models.CharField(default='', max_length=150)),
                ('nome_mae_noiva', models.CharField(default='', max_length=150)),
                ('endereco_pais_noiva', models.CharField(max_length=255)),
                ('celular_pais_noiva', models.CharField(default='', max_length=20)),
                ('religiao_pais_noiva', models.CharField(max_length=100)),
                ('data_provavel_casamento', models.DateField()),
                ('paroquia_casamento', models.CharField(max_length=100)),
                ('ficha_impressa', models.BooleanField(default=False)),
                ('ficha_assinada', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
