# Generated by Django 6.0 on 2026-01-19 00:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_noivomodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoroinhaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('data_nascimento', models.DateField()),
                ('endereco', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2)),
                ('nome_pai', models.CharField(default='', max_length=150)),
                ('celular_pai', models.CharField(default='', max_length=20)),
                ('nome_mae', models.CharField(default='', max_length=150)),
                ('celular_mae', models.CharField(default='', max_length=20)),
                ('nome_responsavel', models.CharField(max_length=150)),
                ('cpf_responsavel', models.CharField(max_length=14)),
                ('endereco_responsavel', models.CharField(max_length=255)),
                ('ficha_impressa', models.BooleanField(default=False)),
                ('ficha_assinada', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='perseveranca_mej_model',
            name='horario',
            field=models.CharField(choices=[('1', 'Perseverança e MEJ - 11 a 14 anos - Quinta às 19:30h - Encontros na Capela NSGraças'), ('2', 'MEJ - 15 a 25 anos - Quinta às 19:30h - Encontros na Capela NSGraças'), ('3', 'Perseverança e MEJ - 11 a 14 anos - Terça às 19:30h - Encontros na Capela NSGraças'), ('4', 'MEJ - 15 a 25 anos - Terça às 19:30h - Encontros na Capela NSGraças')], max_length=2),
        ),
    ]
